name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Auto Deploy Backend to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo "Starting EC2 Deployment..."

            cd ~/sprint1

            echo "Pulling latest code from GitHub..."
            git pull origin main --rebase

            echo "Stopping old containers..."
            docker compose down

            echo "Rebuilding and starting containers..."
            DOCKER_BUILDKIT=0 docker compose up -d --build

            echo "Checking running containers..."
            docker ps

            echo "Deployment completed successfully!"